### ISSUE TITLE
Hosts using imgur instead of github even when 'host using github' is checked

### ISSUE THREAD

**Issue by braydenware** [mark-hahn/auto-host-markdown-image#2]
The setting 'host using github' doesn't change the behavior of the package.

**Comment by mark-hahn** [comment]
I can't repeat the problem.
- what OS/version and atom version are you on?
- did you try restarting atom after changing the setting?
- what is your setting for the github project relative folder?
- does that folder exist?
- was the image copied into that folder?
- can you show me what was pasted into your markdown document?

**Comment by mark-hahn** [comment]
An idea.  Look through your whole markdown document and see if it was pasted somewhere other than where you expected.  It pastes wherever the cursor is, not where you drag it do.

**Comment by braydenware** [comment]
The text shows up at the right place. An example looks like this:

```
![Image inserted by Atom editor package auto-host-markdown-image](http://i.imgur.com/a7kGb2q.png?delhash=Vu5dUSEp6vGw79t)
```

The github project relative folder setting is "images", and the folder images exist. But no files are created in it. I've got a package.json on the top level of the github project that has contents:

{
  "name": "FBI-talk",
  "repository": "https://github.com/braydenware/FBI-talk"
}

Yeah, I tried restarting and reinstalling the package.

**Comment by mark-hahn** [comment]
This is so odd.  The code is very simple.  I'll put a version up with some
debug logging.  If you could try it out I'd appreciate it.  I'll let you
know when it's ready to try.

**Comment by braydenware** [comment]
Actually, it works now for me. I didn't realize this at first, but the version available via atom's package repository is different than the current one on github. I had downloaded it from here first, but then tried reinstalling it inside atom.

**Comment by mark-hahn** [comment]
Wow.  I didn't know that.  I'll fix the repo.

Thanks mucho.

**Comment by mark-hahn** [comment]
FYI:  It is now published correctly including the github hosting feature.
