### ISSUE TITLE
I get Error 400 

### ISSUE THREAD

**Issue by manorius** [mark-hahn/auto-host-markdown-image#3]
Whenever I try to upload to imgur I get error 400

**Auto-host-markdown-image Error:
Error uploading image to imgur: 400**

**Comment by mark-hahn** [comment]
I just tried it and it worked fine.  What settings do you have for the
package?  What OS are you on.  What version Atom?  Version of this
package?  Behind a proxy?

Has it ever worked for you before?  If so then maybe imgur was unavailable
for a while.  If the problem doesn't go away then send me the image and the
markdown file and I'll try them here.

**Comment by mark-hahn** [comment]
Closing due to no response.
