### ISSUE TITLE
Object.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by sdelavega** [mark-hahn/auto-host-markdown-image#6]
Requiring `$` from `atom` is no longer supported.
If you are using `space-pen`, please require `$` from `atom-space-pen-views`. Otherwise require `jquery` instead:
  `{$} = require 'atom-space-pen-views'`
  or
  `$ = require 'jquery'`
Add `"atom-space-pen-views": "^2.0.3"` to your package dependencies.
Or add `"jquery": "^2"` to your package dependencies.

```
Object.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app.asar/exports/atom.js:48:11)
Object.<anonymous> (/Users/sdelavega/.atom/packages/auto-host-markdown-image/lib/drag.coffee:4:1)
Object.<anonymous> (/Users/sdelavega/.atom/packages/auto-host-markdown-image/lib/drag.coffee:29:4)
Module._compile (module.js:452:26)
Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
Module.load (module.js:347:32)
```

**Comment by mark-hahn** [comment]
Thanks for the report.  This is fixed in my source but will not be released until #4 is resolved.
